package com.acite.axlranko.prompt

/**
 * The wizard's UI text, ported from `tools/gen_prompts.py`'s `STRINGS` (both languages kept).
 * Generated, not hand-written: a missing key falls back to the key itself, like `t()` in the script.
 */
internal object PromptStrings {

    fun of(lang: PromptLang): Map<String, String> = when (lang) {
        PromptLang.Chinese -> chinese
        PromptLang.English -> english
    }

    private val chinese: Map<String, String> = mapOf(
        "character_title" to "角色词（置于最前，生成时不会改写）",
        "character_hint" to "例如 (sena_character:1.1), 1girl",
        "suffix_title" to "质量后缀（接在每条提示词最后；留空则不加）",
        "suffix_hint" to "默认 best quality, newest, highres",
        "mode_title" to "模式",
        "mode_sfw" to "SFW — 日常姿态，不写性交",
        "mode_nsfw" to "NSFW — 日常姿态，默认可高暴露",
        "mode_sex" to "SEX — 只从性交体位里抽",
        "exposure_title" to "衣物暴露程度（可多选）",
        "exp_covered" to "遮住 — 校服、正装、婚纱等",
        "exp_casual" to "日常 — 连衣裙、睡衣、便装",
        "exp_revealing" to "暴露 — 泳装、睡裙",
        "exp_open" to "敞开 — 给可敞开的套装加上 open clothes",
        "exp_nude" to "裸体 — 不抽服装，写 nude",
        "sfw_warn" to "SFW 搭配了高暴露（泳装 / 敞开 / 裸体）。仍可生成，提示词里不会写入 sfw/nsfw。",
        "warn_continue" to "继续",
        "warn_back" to "返回修改",
        "clothing_title" to "服装偏好（可多选；选「不限」则该维均匀抽）",
        "chest_title" to "胸部裸露",
        "chest_covered" to "遮住 — 不写胸部标签",
        "chest_cleavage" to "乳沟 — cleavage",
        "chest_out" to "掏出 — breasts out（需敞开或裸体）",
        "chest_nipples" to "乳头 — breasts out + nipples",
        "chest_auto" to "按姿势 — 正面敞开必写 breasts out/nipples，跪趴可加可不加",
        "belly_title" to "腹部裸露",
        "belly_covered" to "遮住 — 不写腹部标签",
        "belly_midriff" to "露腰 — midriff",
        "belly_navel" to "肚脐 — midriff, navel",
        "belly_auto" to "按姿势 — 正面敞开或裸体时写 navel",
        "figure_title" to "体型（单选；「不写」= 不加体型词）",
        "sfw_body_warn" to "SFW 勾了胸部掏出/乳头。仍可生成，提示词里不会写入 sfw/nsfw。",
        "face_title" to "表情（组内可多选：每条从勾选项里抽一个；一条不勾 = 不写；「不限」= 该组整池随机）",
        "face_skip" to "不写",
        "footer_face" to "↑↓ 移动  n/p 上下一组  空格 勾选  Enter 下一步  b 返回  q 放弃",
        "sfw_face_warn" to "SFW 选了偏性交的表情（阿嘿颜 / 高潮 / 痛苦等）。仍可生成，提示词里不会写入 sfw/nsfw。",
        "scene_title" to "场景偏好（可多选）",
        "family_title" to "体位大类（可多选）",
        "fam_face" to "面对面位 — 传教士、交配压、铁砧、站立对面",
        "fam_behind" to "背后位 — 跪趴/平趴后入、反骑",
        "fam_stand_behind" to "站立背后位 — 站立弯腰后入、背对抱插、全尼尔森",
        "fam_side_behind" to "侧背后位 — 汤匙、第七式",
        "fam_girl_on_top" to "女上 — 正骑、蹲骑、反骑、坐抱",
        "fam_hold" to "抱位 — 对面/背对抱插、全尼尔森、坐抱",
        "ratio_title" to "阴道交占比（0–1；肛交权值 = 1 − 该值）",
        "ratio_hint" to "0 = 全肛交，1 = 全阴道，0.7 = 七成阴道。也可输入 0–100。",
        "stage_title" to "性爱阶段占比（相对权重，0 表示不抽）",
        "stage_hint" to "↑↓ 改哪一行；数字同阴道占比。默认只抽性爱中。",
        "invisible_penis_title" to "不可见阴茎（提示词里的 penis 写成 invisible penis）",
        "invisible_penis_hint" to "只有 SEX 阶段会用阴茎词：开启后写成 invisible penis，例如 penis on ass → invisible penis on ass，并且这些提示词写 solo 而不是 1boy, hetero（阴茎看不见时不应该有画面内的男性）。角色词不动。",
        "stage_pose" to "摆姿势 — 性交体位、无阴茎",
        "stage_before" to "性爱前 — 对准、未插入",
        "stage_during" to "性爱中 — 已插入",
        "stage_object_insertion" to "物体插入 — 玩具/物体，无阴茎（随体位走肛或阴道）",
        "stage_fingering" to "手指 — 无阴茎（后穴 anal fingering，阴道 fingering；抱腿的姿势会写 1boy，免得模型多画一只手）",
        "stage_ejaculation" to "射精 — 中出（仍插入）",
        "stage_after" to "性爱后 — 已拔出、精液、扩开（有阴茎）",
        "stage_done" to "完成 — 同性爱后，无阴茎",
        "pussy_shape_title" to "阴部形状（单选）",
        "pussy_hair_title" to "阴毛（单选）",
        "pussy_hint" to "这两个分组只加在已经写了 pussy 的那张图上：阴道通道，或分腿类姿势；肛交通道的图写的是 anus，不加。",
        "pose_title" to "姿态（可多选）",
        "count_title" to "生成条数",
        "any" to "不限",
        "pick_off" to "不写",
        "confirm_title" to "确认并生成",
        "confirm_go" to "生成",
        "confirm_save" to "保存为 Profile",
        "profile_title" to "选择 Profile（或新建一个）",
        "profile_new" to "＋ 新建（运行向导）",
        "profile_save_title" to "Profile 名称",
        "profile_save_hint" to "保存后下次启动可直接选它生成；同名会覆盖",
        "profile_saved" to "已保存 Profile",
        "profile_save_cancelled" to "未保存（已取消覆盖）",
        "profile_save_failed" to "保存失败",
        "profile_overwrite_title" to "同名 Profile 已存在，要覆盖吗？",
        "profile_overwrite_yes" to "覆盖",
        "manifest_title" to "配置总清单（Enter 编辑选中项）",
        "manifest_go" to "生成",
        "manifest_save" to "保存为 Profile",
        "manifest_back" to "返回选择 Profile",
        "manifest_selected" to "已选 {n} 项",
        "manifest_stage_fallback" to "全为 0 → during",
        "footer_manifest" to "↑↓ 移动  Enter 编辑/执行  b 返回  q 放弃",
        "item_character" to "角色词",
        "item_suffix" to "质量后缀",
        "item_mode" to "模式",
        "item_exposure" to "暴露程度",
        "item_clothing" to "服装",
        "item_chest" to "胸部",
        "item_belly" to "腹部",
        "item_figure" to "体型",
        "item_face" to "表情",
        "item_scene" to "场景",
        "item_family" to "体位大类",
        "item_ratio" to "阴道占比",
        "item_stages" to "阶段权重",
        "item_invisible_penis" to "不可见阴茎",
        "item_pussy_shape" to "阴部形状",
        "item_pussy_hair" to "阴毛",
        "item_pose" to "姿态",
        "item_count" to "条数",
        "footer" to "↑↓ 移动  空格 勾选  a 全选  Enter 下一步  b 返回  q 放弃",
        "footer_text" to "输入文字  Enter 下一步  b 返回  q 放弃",
        "empty_character" to "角色词不能为空",
        "need_tty" to "需要在终端里运行向导（stdin 不是 TTY）。",
        "need_exposure" to "至少勾选一档暴露程度。",
    )

    private val english: Map<String, String> = mapOf(
        "character_title" to "Character prefix (immutable, always first)",
        "character_hint" to "e.g. (sena_character:1.1), 1girl",
        "suffix_title" to "Quality suffix (appended to every prompt; blank adds nothing)",
        "suffix_hint" to "Default: best quality, newest, highres",
        "mode_title" to "Mode",
        "mode_sfw" to "SFW — everyday poses, no sex tags",
        "mode_nsfw" to "NSFW — everyday poses, high exposure by default",
        "mode_sex" to "SEX — poses only from the sex list",
        "exposure_title" to "Clothing exposure (multi-select)",
        "exp_covered" to "covered — uniforms, formal, wedding",
        "exp_casual" to "casual — sundress, pajamas, daywear",
        "exp_revealing" to "revealing — swimwear, nightgown",
        "exp_open" to "open — add open clothes on marked outfits",
        "exp_nude" to "nude — skip clothing, write nude",
        "sfw_warn" to "SFW with high exposure (revealing / open / nude). Generation continues; sfw/nsfw are not written into the prompt.",
        "warn_continue" to "Continue",
        "warn_back" to "Go back",
        "clothing_title" to "Clothing preference (multi-select; Any = uniform in the pool)",
        "chest_title" to "Chest exposure",
        "chest_covered" to "covered — no chest tags",
        "chest_cleavage" to "cleavage",
        "chest_out" to "breasts out (needs open clothes or nude)",
        "chest_nipples" to "breasts out + nipples",
        "chest_auto" to "by pose — front+open always breasts out/nipples; kneeling/prone optional",
        "belly_title" to "Belly exposure",
        "belly_covered" to "covered — no belly tags",
        "belly_midriff" to "midriff",
        "belly_navel" to "midriff + navel",
        "belly_auto" to "by pose — navel when front and open/nude",
        "figure_title" to "Figure (single pick; off adds no figure word)",
        "sfw_body_warn" to "SFW with breasts out / nipples. Generation continues; sfw/nsfw are not written into the prompt.",
        "face_title" to "Face (multi-select per group: one of the ticked tags per prompt; none ticked = off; Any = the whole pool)",
        "face_skip" to "off",
        "footer_face" to "↑↓ move  n/p group  Space toggle  Enter next  b back  q quit",
        "sfw_face_warn" to "SFW with sex-leaning face tags (ahegao / orgasm / pain, …). Generation continues; sfw/nsfw are not written into the prompt.",
        "scene_title" to "Scene preference (multi-select)",
        "family_title" to "Pose families (multi-select)",
        "fam_face" to "face to face — missionary, mating press, anvil, standing missionary",
        "fam_behind" to "from behind — kneeling/prone doggy, reverse cowgirl",
        "fam_stand_behind" to "standing from behind — standing doggy, reverse suspended, full nelson",
        "fam_side_behind" to "side from behind — spooning, seventh posture",
        "fam_girl_on_top" to "girl on top — cowgirl, squat, reverse, lap sit",
        "fam_hold" to "held / carried — suspended congress, full nelson, lap sit",
        "ratio_title" to "Vaginal share (0–1; anal weight is 1 minus this)",
        "ratio_hint" to "0 = all anal, 1 = all vaginal, 0.7 = 70% vaginal. 0–100 is also accepted.",
        "stage_title" to "Sex stage share (relative weights; 0 skips that stage)",
        "stage_hint" to "↑↓ picks the row. Numbers work like the vaginal share. Default is during only.",
        "invisible_penis_title" to "Invisible penis (write invisible penis wherever the line says penis)",
        "invisible_penis_hint" to "Only the SEX stages name it: with this on they write invisible penis, e.g. penis on ass → invisible penis on ass, and those lines claim solo instead of 1boy, hetero (a partner in frame would contradict it). The character prefix is left alone.",
        "stage_pose" to "posing — sex pose, no penis",
        "stage_before" to "before — aimed, not inserted",
        "stage_during" to "during — inserted",
        "stage_object_insertion" to "object insertion — toy/object, no penis (anal or vaginal from the pose)",
        "stage_fingering" to "fingering — no penis (anal fingering on anal poses, fingering on vaginal; a pose that holds its own legs writes 1boy instead of solo, or the model adds a third hand)",
        "stage_ejaculation" to "ejaculation — creampie while still in",
        "stage_after" to "after — pulled out, drip, gape, penis still in frame",
        "stage_done" to "done — same as after, no penis",
        "pussy_shape_title" to "Pussy shape (single pick)",
        "pussy_hair_title" to "Pubic hair (single pick)",
        "pussy_hint" to "These two groups ride a prompt that already says pussy — a vaginal channel, or a spread pose. An anal draw names anus and gets neither.",
        "pose_title" to "Poses (multi-select)",
        "count_title" to "How many prompts",
        "any" to "Any",
        "pick_off" to "off",
        "confirm_title" to "Confirm and generate",
        "confirm_go" to "Generate",
        "confirm_save" to "Save as profile",
        "profile_title" to "Choose a profile (or start a new one)",
        "profile_new" to "+ New (run the wizard)",
        "profile_save_title" to "Profile name",
        "profile_save_hint" to "Saved profiles can generate straight away next run; a same-name profile is overwritten",
        "profile_saved" to "Saved profile",
        "profile_save_cancelled" to "Not saved (overwrite declined)",
        "profile_save_failed" to "Save failed",
        "profile_overwrite_title" to "A profile with that name exists; overwrite it?",
        "profile_overwrite_yes" to "Overwrite",
        "manifest_title" to "Configuration (Enter edits the highlighted row)",
        "manifest_go" to "Generate",
        "manifest_save" to "Save as profile",
        "manifest_back" to "Back to profiles",
        "manifest_selected" to "{n} selected",
        "manifest_stage_fallback" to "all zero → during",
        "footer_manifest" to "↑↓ move  Enter edit/run  b back  q quit",
        "item_character" to "Character",
        "item_suffix" to "Quality suffix",
        "item_mode" to "Mode",
        "item_exposure" to "Exposure",
        "item_clothing" to "Clothing",
        "item_chest" to "Chest",
        "item_belly" to "Belly",
        "item_figure" to "Figure",
        "item_face" to "Face",
        "item_scene" to "Scene",
        "item_family" to "Pose families",
        "item_ratio" to "Vaginal share",
        "item_stages" to "Stage weights",
        "item_invisible_penis" to "Invisible penis",
        "item_pussy_shape" to "Pussy shape",
        "item_pussy_hair" to "Pubic hair",
        "item_pose" to "Poses",
        "item_count" to "Count",
        "footer" to "↑↓ move  Space toggle  a all  Enter next  b back  q quit",
        "footer_text" to "type  Enter next  b back  q quit",
        "empty_character" to "Character prefix cannot be empty",
        "need_tty" to "The wizard needs a terminal (stdin is not a TTY).",
        "need_exposure" to "Select at least one exposure level.",
    )
}
